/* 
**  mod_lmsanalitics.c -- Apache sample lmsanalitics module
**  [Autogenerated via ``apxs -n lmsanalitics -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_lmsanalitics.c
**
**  Then activate it in Apache's apache2.conf file for instance
**  for the URL /lmsanalitics in as follows:
**
**    #   apache2.conf
**    LoadModule lmsanalitics_module modules/mod_lmsanalitics.so
**    <Location /lmsanalitics>
**    SetHandler lmsanalitics
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /lmsanalitics and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/lmsanalitics 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_lmsanalitics.c
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"

///
#include <stdio.h>
#include <stdlib.h>
#include <postgresql/libpq-fe.h>
//
#include <json-c/json.h>
//
///

struct structcustomer{
    
     char* name;
     char* lastname;
     char* year;
     char* city;
     char* street;
     int*   nettariff;  
};


//
/* The sample content handler */
static int lmsanalitics_handler(request_rec *r)
{
    if (strcmp(r->handler, "lmsanalitics")) {
        return DECLINED;
    }
    r->content_type = "text/html";      
///
	PGconn *conn = PQconnectdb("host=127.0.0.1 user=u dbname=n password=p");
//
	char *stmNetAssign="SELECT tariffid, t.name FROM assignments a JOIN tariffs t ON (t.id=a.tariffid) WHERE a.customerid=$1 AND t.type=1";

	char *stmAddress="SELECT a.city, a.street FROM customer_addresses c JOIN addresses a ON (c.address_id=a.id) WHERE c.customer_id=$1";
//
	char *paramValues[1];

	char *stmCustomers = "SELECT id, status, name, lastname, ten, ssn, paytime, paytype FROM customers";
	PGresult *resCustomers = PQexec(conn,"SELECT id, status, name, lastname, ten, ssn, paytime, paytype FROM customers");

	int rows = PQntuples(resCustomers);

    //Create customer structure to map intereseting customer data than count them
//struct structcustomer *customers = (struct structcustomer*)malloc(rows*sizeof(struct structcustomer));
	struct structcustomer *customers = malloc(rows*sizeof(struct structcustomer));

    char *customerid;
    for(int i=0; i<rows; i++) {
        customerid=PQgetvalue(resCustomers, i, 0);

        customers[i].name=PQgetvalue(resCustomers, i, 2);

        customers[i].lastname=PQgetvalue(resCustomers, i, 3);

        char year[2];
		size_t s2len = strlen(PQgetvalue(resCustomers, i, 5));
		if(s2len>2)
		{
		    char *ssn=PQgetvalue(resCustomers, i, 5);

			year[0]=ssn[0];
			year[1]=ssn[1];
			customers[i].year=year;
		}

//Assignment
		paramValues[0]=customerid;

  		PGresult *resNetAssign = PQexecParams(conn, stmNetAssign, 1, NULL, paramValues, NULL, NULL, 0);

		customers[i].nettariff=PQgetvalue(resNetAssign, 0, 0);
        
///Address
  		PGresult *resAddress = PQexecParams(conn, stmAddress, 1, NULL, paramValues, 
        NULL, NULL, 0);

		customers[i].city=PQgetvalue(resAddress, 0, 0);

		customers[i].street=PQgetvalue(resAddress, 0, 1);
	}

    //Clean Customers Query
    PQclear( resCustomers );
////Get Cities for counting
	PGresult *resCityList = PQexec(conn,"SELECT distinct(city) FROM addresses");

	const int rowCity = PQntuples(resCityList);
////Get Streets for counting
	PGresult *resStreetList = PQexec(conn,"SELECT distinct(street) FROM addresses");

	const int rowStreet = PQntuples(resStreetList);
////Get Tarrifs
	PGresult *resTariffList = PQexec(conn,"SELECT name, id FROM tariffs WHERE type=1");

	const int rowTariffs = PQntuples(resTariffList);

    ap_rputs("<TABLE border='1'>", r);
	for(int iTariff=0; iTariff<rowTariffs; iTariff++) {
        ap_rputs("<TR><TD colspan='2'>", r);
        ap_rprintf(r,"<BR><B>%s %s</B>",PQgetvalue(resTariffList, iTariff, 0),PQgetvalue(resTariffList, iTariff, 1));
        ap_rputs("</TD></TR>", r);
		for(int i=0; i<rowCity; i++) {
            ap_rputs("<TR><TD >", r);
            ap_rprintf(r,"<BR>%s",PQgetvalue(resCityList, i, 0));
            ap_rputs("</TD>", r);
			int count=0;
			for(int c=0; c<rows; c++) {

                if(customers[c].nettariff!=NULL && strcmp(customers[c].nettariff,PQgetvalue(resTariffList, iTariff, 1))==0)
                {
				    if( customers[c].city && strcmp(customers[c].city,PQgetvalue(resCityList, i, 0))==0)
					    count=count+1;

                }
			}
            ap_rputs("<TD>", r);

            if(rows>40 && count>1)
            {
                count=count/10;

                if(count==0)
                    count=1;

            }
          
            for(int i=0; i<count; i++) {
                ap_rputs("=",r);
            }
            ap_rputs("</TD>", r);
		}
//
	}
    ap_rputs("</TABLE>", r);
	PQclear( resCityList );
    PQclear( resStreetList );

    //if (!r->header_only)
       // ap_rputs("The sample page from mod_lmsanalitics.c bu hu\n", r);
    return OK;
}

static void lmsanalitics_register_hooks(apr_pool_t *p)
{
    ap_hook_handler(lmsanalitics_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA lmsanalitics_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    lmsanalitics_register_hooks  /* register hooks                      */
};

